services:
  backend:
    image: clausmerderet/bank_api:latest
    ports:
      - "4111:4111"
    networks:
      - bank-network

  tests:
    build: .
    environment:
      - BACKEND_URL=http://backend:4111/api
    depends_on:
      - backend
    networks:
      - bank-network
    volumes:
      - ./reports/allure:/app/reports/allure

networks:
  bank-network:
    driver: bridge
