apiVersion: v1
kind: Deployment

metadata:
  name:
    backend

spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  templates:
    metadata:
      labels:
        app: backend
  spec:
    containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
          - containerPort: 4111

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 4111
      targetPort: 4111
  type: NodePort