name: Run tests

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start app
        run: make start-app

      - name: Run tests
        run: make run-tests

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure/